import { MapBounds } from './types';

export function generateKML(
  imageDataUrl: string,
  bounds: MapBounds,
  name: string = 'PlayMat Magic Overlay'
): string {
  // Convert data URL to just the base64 part for embedding
  // In practice, for Google Earth, we'd need to host the image or embed it
  // For KML export, we'll reference a local file
  const kml = `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>${escapeXml(name)}</name>
    <description>Generated by PlayMat Magic - Custom Children's Play Mat</description>
    <GroundOverlay>
      <name>${escapeXml(name)}</name>
      <description>Custom playmat overlay generated from satellite imagery</description>
      <Icon>
        <href>playmat.png</href>
      </Icon>
      <LatLonBox>
        <north>${bounds.north}</north>
        <south>${bounds.south}</south>
        <east>${bounds.east}</east>
        <west>${bounds.west}</west>
        <rotation>0</rotation>
      </LatLonBox>
    </GroundOverlay>
  </Document>
</kml>`;
  return kml;
}

function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

export function downloadKML(kmlContent: string, filename: string = 'playmat-magic.kml') {
  const blob = new Blob([kmlContent], { type: 'application/vnd.google-earth.kml+xml' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadImage(dataUrl: string, filename: string = 'playmat-magic.png') {
  const a = document.createElement('a');
  a.href = dataUrl;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
}
